name: MLflow Model Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install mlflow scikit-learn
        sudo apt-get install -y sqlite3
    
    - name: Run MLflow server and test
      run: |
        mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000 &
        sleep 15
        
        python main.py
        
        ACCURACY=$(sqlite3 mlflow.db "SELECT value FROM metrics WHERE key = 'accuracy' ORDER BY timestamp DESC LIMIT 1;")
        echo "Last accuracy: $ACCURACY"
    
        if (( $(echo "$ACCURACY < 0.9" | bc -l) )); then
          echo "Error: Accuracy $ACCURACY is below 0.9"
          exit 1
        fi